# docker-compose.yml
version: '3.8'

services:
  node-api-sample:
    container_name: node-api-sample
    hostname: node-api-sample
    image: node-api-sample:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=pipoca150
      - DB_NAME=nodeTeste
      - JWT_SECRET=mySecretKeyJwt